default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: devrails
  password: <%= ENV['expense_regulator_count_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: expense_regulator_count_development

test:
  <<: *default
  database: expense_regulator_count_test

production:
  <<: *default
  database: expense_regulator_count_production
