default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: devrails
  password: <%= ENV['Expense_Regulator_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: Expense_Regulator_development

test:
  <<: *default
  database: Expense_Regulator_test

production:
  <<: *default
  database: Expense_Regulator_production
